language: java

jdk:
  - oraclejdk9

notifications:
  email: false
  webhooks: 
    urls:
      - https://hook.rofl.wtf/
    on_success: always
    on_failure: always
    on_start: change
    on_cancel: never
    on_error: always